### ISSUE TITLE
Questions about pre-trained model checkpoints

### ISSUE THREAD

**Issue by ghqshuai** [yuyongcan/Benchmarking_Test-Time_Adaptation_against_Distribution_Shifts_in_Image_Classification#1]
Hello, can you provide the directory CKPT where the pre-trained model checkpoint is located

**Comment by yuyongcan** [comment]
I have already updated it in the readme. You can download the ckpt directory from https://drive.google.com/drive/folders/14GWvsEI5pDc3Mm7vqyELeBPuRUSPt-Ao

**Comment by ghqshuai** [comment]
Ok, thank you

**Comment by ghqshuai** [comment]
Hello, I'm bothering you again.
When I want to check Hendrycks2020AugMix_ResNeXt.pt，I met an Error：Error (s) in loading state_dict for Hendrycks2020AugMixResNeXtNet.
And my code is following
"import torch
from robustbench.models.Hendrycks2020AugMix_ResNeXt import Hendrycks2020AugMixResNeXtNet
model = Hendrycks2020AugMixResNeXtNet()  
model.load_state_dict(torch.load('Hendrycks2020AugMix_ResNeXt.pt', map_location=torch.device('cpu')))
print(model.state_dict())"
it works when I check ‘WideResNet.pt’

**Comment by yuyongcan** [comment]
I would like to know does this error exists if you import model from src.models.
Try that replace "from robustbench.models.Hendrycks2020AugMix_ResNeXt import Hendrycks2020AugMixResNeXtNet"
with "from src.model.Hendrycks2020AugMix_ResNeXtNet import Hendrycks2020AugMixResNeXtNet"

**Comment by ghqshuai** [comment]
I tried but the result is still the same

**Comment by yuyongcan** [comment]
I‘m sorry that I can reproduce your error again. Can you describe the error message specifically?
That's my code:
![image](https://github.com/yuyongcan/Benchmark-TTA/assets/83764015/4c31483e-bc38-422b-9cb1-ff61e7700537)

**Comment by ghqshuai** [comment]
Maybe there were some problems with my path before, but they have been solved now. Thank you
